// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ-oAi9BufWiOIiS_0Gf5ZKIiFCZaQWes',
    appId: '1:442338865995:web:6060914e03c656bdfa6ece',
    messagingSenderId: '442338865995',
    projectId: 'intelifridge',
    authDomain: 'intelifridge.firebaseapp.com',
    storageBucket: 'intelifridge.appspot.com',
    measurementId: 'G-GHBNQ0QW9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-aZsGXleRe9_B8OF-7Siqa1kLS0grKDk',
    appId: '1:442338865995:android:ec3c69429205479bfa6ece',
    messagingSenderId: '442338865995',
    projectId: 'intelifridge',
    storageBucket: 'intelifridge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBncG6ABcgfoXnuhpmVKQ5PqRycLZUC5Zc',
    appId: '1:442338865995:ios:d214c0391c26f852fa6ece',
    messagingSenderId: '442338865995',
    projectId: 'intelifridge',
    storageBucket: 'intelifridge.appspot.com',
    iosBundleId: 'com.example.intelifridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBncG6ABcgfoXnuhpmVKQ5PqRycLZUC5Zc',
    appId: '1:442338865995:ios:d214c0391c26f852fa6ece',
    messagingSenderId: '442338865995',
    projectId: 'intelifridge',
    storageBucket: 'intelifridge.appspot.com',
    iosBundleId: 'com.example.intelifridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ-oAi9BufWiOIiS_0Gf5ZKIiFCZaQWes',
    appId: '1:442338865995:web:ec2745b363be17f8fa6ece',
    messagingSenderId: '442338865995',
    projectId: 'intelifridge',
    authDomain: 'intelifridge.firebaseapp.com',
    storageBucket: 'intelifridge.appspot.com',
    measurementId: 'G-CFJ1GPX01K',
  );
}
